on:
  pull_request:
    types: [opened, edited]
name: conventional-release-labels
jobs:
  label:
    runs-on: ubuntu-latest
    name: Lint PR
    steps:
      - name: Conventional Labeler
        uses: action-runner/conventional-labeler@2.0.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the output
        run: echo "The labels were ${{ steps.label.outputs.labels }}"
