on:
  push:
    branches:
      - dev
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          default-branch: dev
          release-type: node
          changelog-types: '[{"type":"feat","section":"✨ Features","hidden":false},{"type":"fix","section":"🐛 Bug Fixes","hidden":false},{"type":"chore","section":"🏗 Chores","hidden":false}]'
          prerelease: true
